// react/files/after/src/components/Article/ArticleMeta.js
import ArticleActions from './ArticleActions';
import { Link } from 'react-router-dom';
import React from 'react';
const ArticleMeta = props => {
const article = props.article;
return (
<div className="article-meta">
<Link to={`/@${article.author.username}`}>
<img src={article.author.image} alt={article.author.username} />
</Link>
<div className="info">
<Link to={`/@${article.author.username}`} className="author">
{article.author.username}
</Link>
<span className="date">
{new Date(article.createdAt).toDateString()}
</span>
</div>
<ArticleActions canModify={props.canModify} article={article} />
</div>
);
};
export default ArticleMeta;

// angular/files/after/app/shared/article-helpers/article-meta.component.ts
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { Article } from "../../core/models/article.model";
import { RouterLink } from "@angular/router";
import { DatePipe } from "@angular/common";
@Component({
selector: "app-article-meta",
templateUrl: "./article-meta.component.html",
changeDetection: ChangeDetectionStrategy.OnPush,
imports: [RouterLink, DatePipe],
standalone: true,
})
export class ArticleMetaComponent {
@Input() article!: Article;
}

<div class="article-meta">
<a [routerLink]="['/profile', article.author.username]">
<img [src]="article.author.image" />
</a>
<div class="info">
<a class="author" [routerLink]="['/profile', article.author.username]">
{{ article.author.username }}
</a>
<span class="date">
{{ article.createdAt | date : "longDate" }}
</span>
</div>
<ng-content></ng-content>
</div>
