// react/files/after/components/Article/Comment.js
import DeleteButton from './DeleteButton';
import { Link } from 'react-router-dom';
import React from 'react';
const Comment = props => {
const comment = props.comment;
const show = props.currentUser &&
props.currentUser.username === comment.author.username;
return (
<div className="card">
<div className="card-block">
<p className="card-text">{comment.body}</p>
</div>
<div className="card-footer">
<Link
to={`/@${comment.author.username}`}
className="comment-author">
<img src={comment.author.image} className="comment-author-img" alt={comment.author.username} />
</Link>
&nbsp;
<Link
to={`/@${comment.author.username}`}
className="comment-author">
{comment.author.username}
</Link>
<span className="date-posted">
{new Date(comment.createdAt).toDateString()}
</span>
<DeleteButton show={show} slug={props.slug} commentId={comment.id} />
</div>
</div>
);
};
export default Comment;

// vue/files/after/src/components/Comment.vue
<template>
<div class="card">
<div class="card-block">
<p class="card-text">{{ comment.body }}</p>
</div>
<div class="card-footer">
<a href="" class="comment-author">
<img :src="comment.author.image" class="comment-author-img" />
</a>
<router-link
class="comment-author"
:to="{ name: 'profile', params: { username: comment.author.username } }"
>
{{ comment.author.username }}
</router-link>
<span class="date-posted">{{ comment.createdAt | date }}</span>
<span v-if="isCurrentUser" class="mod-options">
<i class="ion-trash-a" @click="destroy(slug, comment.id)"></i>
</span>
</div>
</div>
</template>
<script>
import { mapGetters } from "vuex";
import { COMMENT_DESTROY } from "@/store/actions.type";
export default {
name: "RwvComment",
props: {
slug: { type: String, required: true },
comment: { type: Object, required: true }
},
computed: {
isCurrentUser() {
if (this.currentUser.username && this.comment.author.username) {
return this.comment.author.username === this.currentUser.username;
}
return false;
},
...mapGetters(["currentUser"])
},
methods: {
destroy(slug, commentId) {
this.$store.dispatch(COMMENT_DESTROY, { slug, commentId });
}
}
};
</script>
