// react/files/after/src/components/Article/index.js
import ArticleMeta from './ArticleMeta';
import CommentContainer from './CommentContainer';
import React from 'react';
import agent from '../../agent';
import { connect } from 'react-redux';
import marked from 'marked';
import { ARTICLE_PAGE_LOADED, ARTICLE_PAGE_UNLOADED } from '../../constants/actionTypes';
const mapStateToProps = state => ({
...state.article,
currentUser: state.common.currentUser
});
const mapDispatchToProps = dispatch => ({
onLoad: payload =>
dispatch({ type: ARTICLE_PAGE_LOADED, payload }),
onUnload: () =>
dispatch({ type: ARTICLE_PAGE_UNLOADED })
});
class Article extends React.Component {
componentWillMount() {
this.props.onLoad(Promise.all([
agent.Articles.get(this.props.match.params.id),
agent.Comments.forArticle(this.props.match.params.id)
]));
}
componentWillUnmount() {
this.props.onUnload();
}
render() {
if (!this.props.article) {
return null;
}
const markup = { __html: marked(this.props.article.body, { sanitize: true }) };
const canModify = this.props.currentUser &&
this.props.currentUser.username === this.props.article.author.username;
return (
<div className="article-page">
<div className="banner">
<div className="container">
<h1>{this.props.article.title}</h1>
<ArticleMeta
article={this.props.article}
canModify={canModify} />
</div>
</div>
<div className="container page">
<div className="row article-content">
<div className="col-xs-12">
<div dangerouslySetInnerHTML={markup}></div>
<ul className="tag-list">
{
this.props.article.tagList.map(tag => {
return (
<li
className="tag-default tag-pill tag-outline"
key={tag}>
{tag}
</li>
);
})
}
</ul>
</div>
</div>
<hr />
<div className="article-actions">
</div>
<div className="row">
<CommentContainer
comments={this.props.comments || []}
errors={this.props.commentErrors}
slug={this.props.match.params.id}
currentUser={this.props.currentUser} />
</div>
</div>
</div>
);
}
}
export default connect(mapStateToProps, mapDispatchToProps)(Article);

// vue/files/after/src/views/Article.vue
<template>
<div class="article-page">
<div class="banner">
<div class="container">
<h1>{{ article.title }}</h1>
<RwvArticleMeta :article="article" :actions="true"></RwvArticleMeta>
</div>
</div>
<div class="container page">
<div class="row article-content">
<div class="col-xs-12">
<div v-html="parseMarkdown(article.body)"></div>
<ul class="tag-list">
<li v-for="(tag, index) of article.tagList" :key="tag + index">
<RwvTag
:name="tag"
className="tag-default tag-pill tag-outline"
></RwvTag>
</li>
</ul>
</div>
</div>
<hr />
<div class="article-actions">
<RwvArticleMeta :article="article" :actions="true"></RwvArticleMeta>
</div>
<div class="row">
<div class="col-xs-12 col-md-8 offset-md-2">
<RwvCommentEditor
v-if="isAuthenticated"
:slug="slug"
:userImage="currentUser.image"
>
</RwvCommentEditor>
<p v-else>
<router-link :to="{ name: 'login' }">Sign in</router-link>
or
<router-link :to="{ name: 'register' }">sign up</router-link>
to add comments on this article.
</p>
<RwvComment
v-for="(comment, index) in comments"
:slug="slug"
:comment="comment"
:key="index"
>
</RwvComment>
</div>
</div>
</div>
</div>
</template>
<script>
import { mapGetters } from "vuex";
import marked from "marked";
import store from "@/store";
import RwvArticleMeta from "@/components/ArticleMeta";
import RwvComment from "@/components/Comment";
import RwvCommentEditor from "@/components/CommentEditor";
import RwvTag from "@/components/VTag";
import { FETCH_ARTICLE, FETCH_COMMENTS } from "@/store/actions.type";
export default {
name: "rwv-article",
props: {
slug: {
type: String,
required: true
}
},
components: {
RwvArticleMeta,
RwvComment,
RwvCommentEditor,
RwvTag
},
beforeRouteEnter(to, from, next) {
Promise.all([
store.dispatch(FETCH_ARTICLE, to.params.slug),
store.dispatch(FETCH_COMMENTS, to.params.slug)
]).then(() => {
next();
});
},
computed: {
...mapGetters(["article", "currentUser", "comments", "isAuthenticated"])
},
methods: {
parseMarkdown(content) {
return marked(content);
}
}
};
</script>
